### ISSUE TITLE
Create a resources page

### ISSUE THREAD

**Issue by OrkoHunter** [kossiitkgp/kwoc#13]
Source https://developers.google.com/open-source/gsoc/resources/

Add
 - Timeline
 - Student and Mentor manuals
 - Mailing lists/Facebook group
 - Media 
 - FAQ
 - Contact

**Comment by kshitij10496** [comment]
I think this is done !
Great work @OrkoHunter 
Closing this for now

**Comment by kshitij10496** [comment]
Fixed by #60
