### ISSUE TITLE
Use a single color scheme across website

### ISSUE THREAD

**Issue by DefCon-007** [kossiitkgp/kwoc#14]
At some place, the things are blue and at others they are green. We have to fix a single color scheme.

**Comment by AvijitGhosh82** [comment]
#3b1548
#f3f0f4
#6e6f71

**Comment by DefCon-007** [comment]
@AvijitGhosh82 Can you make a PR ?

**Comment by AvijitGhosh82** [comment]
Those are the color hex codes, not commit hashes.

**Comment by DefCon-007** [comment]
I know they colour hex codes. I am saying can you make a PR adding them to the page

**Comment by nitinkgp23** [comment]
Time to close this issue ?
