### ISSUE TITLE
Add notification for successful/error on  form submission for both student and mentor on form

### ISSUE THREAD

**Issue by DefCon-007** [kossiitkgp/kwoc#19]
The current code here :
https://github.com/kossiitkgp/kwoc/blob/master/templates/index.html#L490-L496
It gives a simple a Javascript alert and we want a to alert about the status of submission to the user below the form only.

**Comment by kshitij10496** [comment]
@kossiitkgp/maintainers 
How about flashing a message corresponding to the situation and redirecting the user to a resource section ?
