### ISSUE TITLE
URLs not routeing properly

### ISSUE THREAD

**Issue by kshitij10496** [kossiitkgp/kwoc#48]
`/student-register` and `/project-register` are not routeing to the expected pages.
Also, on clicking `Apply`, it redirects to the `Contact` section.

**Comment by DefCon-007** [comment]
There is no specified page for both

**Comment by DefCon-007** [comment]
@kshitij10496 Try doing a hard referesh because apply one working fine for me

**Comment by nitinkgp23** [comment]
Both the things working fine for me too.
